name: Continuous Delivery

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1/10 * *"
  push:
    branches:
      - "main"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run crawler script
        shell: bash
        run: python crawler.py

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Go Build
        run: go build -o . main.go

      - name: Generate ICS files
        run: ./main

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: docs/*.html docs/*.ics data/*.txt
          commit_message: update calendar data automatically
          commit_user_name: Muhan Li
          commit_user_email: limuhan@msn.com

      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "::set-output name=msg::$(git log -1 --pretty=%s)"

      - name: Update README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: README.md
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          commit_user_name: Muhan Li
          commit_user_email: limuhan@msn.com
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
