name: Continuous Delivery

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1/10 * *"
  push:
    branches:
      - "main"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run crawler script
        shell: bash
        run: python crawler.py

      - name: Setup Haskell and Cabal
        uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.2.8
          cabal-version: 3.10.1.0

      - name: Configure and build
        run: |
          cabal configure --enable-tests --enable-benchmarks --disable-documentation
          cabal build all

      - name: Generate ICS files
        run: cabal run

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: docs/*.html docs/*.ics data/*.txt
          commit_message: update calendar data automatically
          commit_user_name: Muhan Li
          commit_user_email: limuhan@msn.com
          commit_author: Muhan Li <limuhan@msn.com>

      - name: Get last commit message
        id: last-commit-message
        run: echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Update README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: README.md
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          commit_user_name: Muhan Li
          commit_user_email: limuhan@msn.com
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
