name: Continuous Integration

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:

  llm:
    name: LLM Dry Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout vLLM
        uses: actions/checkout@v4
        with:
          repository: "vllm-project/vllm"
          ref: "v0.7.2"

      - name: Install dependencies
        run: |
          sudo apt-get update  -y
          sudo apt-get install -y gcc-12 g++-12 libnuma-dev jq
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12

      - name: Build vLLM
        run: |
          pip install --upgrade pip
          pip install "cmake>=3.26" wheel packaging ninja "setuptools-scm>=8" numpy
          pip install -v -r requirements-cpu.txt --extra-index-url https://download.pytorch.org/whl/cpu
          sudo -E VLLM_TARGET_DEVICE=cpu python setup.py install

      - name: Run models
        run: vllm serve Qwen/Qwen2.5-1.5B-Instruct &> vllm.log &

      - name: Wait for the server
        run: |
          sleep 60   # for debugging, small models can be run with ~40s
          cat vllm.log
          while ! grep -q "running on http://0.0.0.0:8000" vllm.log; do
              sleep 1
          done

      - name: Show logs
        run: cat vllm.log

      - name: Test the server
        run: curl --retry 5 --retry-delay 10 http://localhost:8000/v1/models

      - name: Demo chat
        run: |
          curl http://localhost:8000/v1/chat/completions \
          -o response.json \
          -H "Content-Type: application/json" \
          -d '{
              "model": "Qwen/Qwen2.5-1.5B-Instruct",
              "messages": [
                  {"role": "system", "content": "You are a technical expert."},
                  {"role": "user", "content": "What is GitHub Actions?"}
              ]
          }'

      - name: Show response
        run: cat response.json | jq . || cat response.json

  crawler:
    name: Crawler Dry Run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run crawler script
        shell: bash
        run: python crawler.py

      - name: Run global scripts
        shell: bash
        run: |
          for script in global/*/main.py; do
            cd $(dirname $script)
            python $(basename $script)
          done

  parser:
    name: Parser Dry Run
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc: [ "9.6", "9.8" ]
        cabal: [ "3.10", "latest" ]
        include:
          - ghc: "9.2.8"
            cabal: "3.10.1.0"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell ${{ matrix.ghc }} with Cabal ${{ matrix.cabal }}
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Configure the build
        run: |
          cabal configure --enable-tests --enable-benchmarks --disable-documentation
          cabal build --dry-run

      - name: Build
        run: cabal build all

      - name: Run tests
        run: cabal test all

      - name: Check cabal file
        run: cabal check

      - name: Run parser
        run: cabal run

      - name: Checkout files
        run: |
          pwd
          ls -la
          ls -la docs

  hlint:
    name: HLint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - name: "Set up HLint"
        uses: haskell-actions/hlint-setup@v2

      - name: "Run HLint"
        uses: haskell-actions/hlint-run@v2
        with:
          path: parser/
          fail-on: warning

  pylint:
    name: Pylint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Analyzing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
