name: ICS Generator

on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Build
        run: go build -o . main

      - name: Generate ICS
        run: ./main

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: docs/*.html docs/*.ics
          commit_message: generate .ics file automatically
          commit_user_name: bugstep
          commit_user_email: github@isaacx.com
